# Input data
input_w: 1024                  
input_h: 1024                  
age_min: 20                  
age_max: 70  
# Training hyperparameters                 
batch_size: 2                 
epochs: 20    
# Optimizer parameters               
lr: 0.0001         
beta_1: 0.9                   
beta_2: 0.999
weight_decay: 0.0005  
# Learning rate scheduler                  
step_size: 10                
gamma: 0.1                                 
# Tensorboard log options
image_save_iter: 3000         
image_log_iter: 1000         
log_iter: 10                  
# Loss weight
w:
  recon: 10
  class: 0.1
  adver: 1
  dis: 1
  gp: 1
  tv: 0